### ISSUE TITLE
ScriptError: Authorization is required to perform that action.

### ISSUE THREAD

**Issue by M4FFS** [alexwforsythe/code-blocks#104]
Add-Ons > code-blocks > Start

ScriptError: Authorization is required to perform that action. (in sidebar)

**Comment by ianhyzy** [comment]
Chrome blocks the pop-up that comes up that prompts you to authorize it, did you manually allow it?

**Comment by M4FFS** [comment]
No popup attempt is made at all

**Comment by alexwforsythe** [comment]
Hi @M4FFS. We are currently tracking this error in #53, so I'm going to close this as a duplicate.

The short explanation is that this is a bug with Google App Script which occurs when you have multiple accounts logged into Drive. You should be able to work around it by logging out of all accounts except the one you need to edit the document.

Feel free to reopen this issue if this solution doesn't solve your problem.
