### ISSUE TITLE
Add the ability to auto indent based on language

### ISSUE THREAD

**Issue by dkelly-sighter** [alexwforsythe/code-blocks#11]

**Comment by alexwforsythe** [comment]
This would be cool, but it's a lot more work to take on code formatting and I don't really have that kind of time. This add-on's syntax-highlighting feature is powered by [highlight.js](https://github.com/isagalaev/highlight.js/), which doesn't support any kind of formatting to my knowledge.

That being said, we could offer the option to toggle between spaces and tabs.
