### ISSUE TITLE
Supporting Solidity Programming Language

### ISSUE THREAD

**Issue by salanfe** [alexwforsythe/code-blocks#110]
solidity https://github.com/ethereum/solidity

used for Ethereum blockchain Smart Contract development https://ethereum.org/

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> Code Blocks is built with [highlight.js](https://highlightjs.org/) and can only provide syntax highlighting for languages that are supported by that library.
>
> If you'd like to see Code Blocks support a language that is not yet implemented by highlight.js, please refer to [their page on requesting new languages](http://highlightjs.readthedocs.io/en/latest/language-requests.html).
