### ISSUE TITLE
I am trying the codeblocks in google docs. I found the syntax highlighting not complete

### ISSUE THREAD

**Issue by sant527** [alexwforsythe/code-blocks#116]
I have few linux commands and code blocks for google docs is not showing the syntax properly

What i am getting in google docs

![google_docs_code_block](https://user-images.githubusercontent.com/6462531/66730508-eb6bc580-ee6f-11e9-9693-d323945e6539.png)

what i am expecting or what i get in sublime text:

![google_docs_code_block2](https://user-images.githubusercontent.com/6462531/66730522-f888b480-ee6f-11e9-9154-d0afca88ad7d.png)

**Comment by AugustM** [comment]
[I'm not the developer, I'm just a user.]

Code Blocks uses the highlight.js javascript library to do the actual parsing. Syntax errors can be addressed by the folks who maintain that library. Right now, they are dependent on whoever contributed the module for any particular language to maintain that language. You might volunteer.

I found a syntax error in how Code Blocks handles VIM files -- it highlights keywords even when they are part of comment text. I have a note in to the highlight.js folks just this morning asking how I might contribute to fixing that. I have no idea when I'll hear back.

In any case, the syntax issues come from the highlight.js library, not Code Blocks.

I hope this helps,
August

.

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> If you'd like to see Code Blocks update or fix support for an existing language:
> 1. Check if the [latest version of highlight.js](https://github.com/highlightjs/highlight.js/releases) already includes the update. If it does, submit a PR to this repository that bumps the highlight.js version in [`package.json`](https://github.com/alexwforsythe/code-blocks/blob/master/package.json).
> 2. If highlight.js does not yet include the update, please submit an issue on [their issue tracker](https://github.com/highlightjs/highlight.js/issues).
