### ISSUE TITLE
Syntax highlighting for golang not quite right when using function signature to indicate function type

### ISSUE THREAD

**Issue by saxon-milton** [alexwforsythe/code-blocks#117]
I am finding that if I am using a function signature as a type e.g.
`var someFunc func(a int) error`
then the same colour will be used for lines after it. I have found that it's because there's no curly braces, so it thinks the function signature is continuing. If I add curly braces like this (which is not valid golang):
`var someFunc func(a int) error {}`
then it works.

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> If you'd like to see Code Blocks update or fix support for an existing language:
> 1. Check if the [latest version of highlight.js](https://github.com/highlightjs/highlight.js/releases) already includes the update. If it does, submit a PR to this repository that bumps the highlight.js version in [`package.json`](https://github.com/alexwforsythe/code-blocks/blob/master/package.json).
> 2. If highlight.js does not yet include the update, please submit an issue on [their issue tracker](https://github.com/highlightjs/highlight.js/issues).
