### ISSUE TITLE
Live code highlighting?

### ISSUE THREAD

**Issue by ParthaEth** [alexwforsythe/code-blocks#118]
This is a feature request if it doesn't already exists. Can the ad on highlight code while being typed? I know the question would be why would any one type code on google doc and not a dedicated IDE. But there are times like a quick explanation, white board coding interview etc.

**Comment by AugustM** [comment]
IMHO as a user, not the developer, that would be a huge project, way beyond the current scope of this GDocs extension.

Personally, I like the idea. I'm working on my own workflow tools to use Google Docs for writing code in an Expository or Literate Programming style. On-the-fly highlighting would be cool, but I know enough about the layers involved to know that you'd have better luck convincing Google to create a Docs-compatible IDE that would do it.

**Comment by alexwforsythe** [comment]
See https://github.com/alexwforsythe/code-blocks#real-time-syntax-highlighting
