### ISSUE TITLE
ScriptError in Google Docs

### ISSUE THREAD

**Issue by SomethingGeneric** [alexwforsythe/code-blocks#128]
`ScriptError: Authorization is required to perform that action.` is displayed in the addon pane, and the only function that works correctly is the language select button

**Comment by ShivanshJ** [comment]
I have been receiving the same error for a very long time!

**Comment by SomethingGeneric** [comment]
@ShivanshJ and haven't been able to figure out why? (Neither can i)

**Comment by j-ts** [comment]
Duplicate of #114

**Comment by SomethingGeneric** [comment]
@j-ts so it is. Sorry!
