### ISSUE TITLE
Please add support for Powershell/DSC

### ISSUE THREAD

**Issue by artisticcheese** [alexwforsythe/code-blocks#13]
Example with coloring from Visual Studio is below

![image](https://cloud.githubusercontent.com/assets/13176884/21967154/406a573e-db47-11e6-8739-adb12f11cc93.png)

**Comment by alexwforsythe** [comment]
Code Blocks is powered by [highlight.js](https://highlightjs.org/) and can only provide syntax highlighting for languages that it supports. Unfortunately, DSC is not implemented yet. Please refer to their page on requesting new languages, found [here](http://highlightjs.readthedocs.io/en/latest/language-requests.html).

That said, I was able to add PowerShell.
