### ISSUE TITLE
Python Interpretter/Console

### ISSUE THREAD

**Issue by pelboothroyd** [alexwforsythe/code-blocks#131]
I write worksheets for people learning Python, it would be useful to have a formatter including the console/interpreter prompts
```
>>>
...
```
To help students realise when we are playing with commands, and when I wish them to use programs.

At present, I format the code, then have to insert the >>> ... and recolour them.

**Comment by SomethingGeneric** [comment]
I agree with you that that'd be helpful.

However, per the README:

Code Blocks is built with highlight.js and can only provide syntax highlighting for languages that are supported by that library. If you'd like to see Code Blocks support a language that is not yet implemented by highlight.js, please refer to their page on requesting new languages, found [here](https://highlightjs.readthedocs.io/en/latest/language-requests.html)
