### ISSUE TITLE
ToS to allow company use

### ISSUE THREAD

**Issue by jseppi** [alexwforsythe/code-blocks#137]
Thanks for the great add-on!

The Terms of Service state that "Permission is granted to temporarily download multiple copies of Code Blocks per device for **personal**, non-commercial transitory viewing only."

Would you consider allowing companies to use this add-on so that employees could use it during work?

**Comment by alexwforsythe** [comment]
Hi @jseppi! Thanks for bringing this to my attention. I've updated the TOS to include commercial use at this commit: https://github.com/alexwforsythe/code-blocks/commit/8ba23342b0e5c2438ce80ed8cdc6a00e23e1b86f

See the official website for the updated TOS:
https://www.alexwforsythe.com/code-blocks/terms-of-service

**Comment by alexwforsythe** [comment]
FYI @dijitali & @tristen

**Comment by jseppi** [comment]
Thanks so much, @alexwforsythe!
