### ISSUE TITLE
no start option

### ISSUE THREAD

**Issue by veronewra** [alexwforsythe/code-blocks#149]
I installed code blocks, but when I click add-ons->code blocks the only option is "help", and when I click on that it says to click a non-existent start button. This is for windows 10, using firefox. Code Blocks works on my ubuntu virtual machine though!

**Comment by kevorb** [comment]
+1

**Comment by ln56b** [comment]
+1

**Comment by KerronKing** [comment]
+1

**Comment by alexwforsythe** [comment]
Does your browser's JavaScript console display any errors when you open the document? If so, can you post a screenshot?

**Comment by ln56b** [comment]
Hi Alex,

I tried again after seeing your message and I now get the "start" button. I am on a MacBook Pro Catalina. I basically re-installed it.

Solved for me. Thanks.

**Comment by alexwforsythe** [comment]
Glad it worked out! Feel free to reopen this issue if you encounter it again.
