### ISSUE TITLE
Kotlin code formatting doesn't recognize backtick identifiers

### ISSUE THREAD

**Issue by AnmAtAnm** [alexwforsythe/code-blocks#152]
For the kotlin code:
```
 @Test
 fun `reverse() should reverse item order`() {
   assertEquals(listOf(1,2,3).reversed(), listOf(3,2,1))
 }
```

I expected:
![image](https://user-images.githubusercontent.com/9916202/87709474-2c736c00-c759-11ea-8b39-c193a33be54b.png)

but got:
![image](https://user-images.githubusercontent.com/9916202/87709507-3a28f180-c759-11ea-8633-596d4f689a49.png)

See "Names for test methods" under [Naming Rules](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules).

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> If you'd like to see Code Blocks update or fix support for an existing language:
> 1. Check if the [latest version of highlight.js](https://github.com/highlightjs/highlight.js/releases) already includes the update. If it does, submit a PR to this repository that bumps the highlight.js version in [`package.json`](https://github.com/alexwforsythe/code-blocks/blob/master/package.json).
> 2. If highlight.js does not yet include the update, please submit an issue on [their issue tracker](https://github.com/highlightjs/highlight.js/issues).
