### ISSUE TITLE
no start option 

### ISSUE THREAD

**Issue by HamidaPremani** [alexwforsythe/code-blocks#156]
would make a big difference , if I can get it to work . Installed it , but not getting an option to start it .

**Comment by alexwforsythe** [comment]
Does your browser's JavaScript console display any errors when you open the document? If so, can you post a screenshot?

**Comment by HamidaPremani** [comment]
Initially , was getting only help option , but got the start option eventually after few hours and I am LOVING it !
Thank you so much

**Comment by alexwforsythe** [comment]
Glad it worked out! Feel free to reopen this issue if you encounter it again.
