### ISSUE TITLE
Adding a Commercial License

### ISSUE THREAD

**Issue by Jinzuu** [alexwforsythe/code-blocks#159]
Currently, the licensing term does not allow us to use the Plugin at our company.
Are there any plans to extend this to commercial use?

**Comment by alexwforsythe** [comment]
Hi @Jinzuu! Thanks for bringing this to my attention. I've updated the TOS to include commercial use at this commit: https://github.com/alexwforsythe/code-blocks/commit/8ba23342b0e5c2438ce80ed8cdc6a00e23e1b86f

See the official website for the updated TOS:
https://www.alexwforsythe.com/code-blocks/terms-of-service

**Comment by Jinzuu** [comment]
Hi @alexwforsythe . Thanks for adding the commercial terms.
Can you elaborate what "transitory viewing" means? I do have trouble understanding that and I want to understand if we are now allowed to use your plugin in our day2day-business activities or not.
