### ISSUE TITLE
Couldn't get theme.

### ISSUE THREAD

**Issue by ursuad** [alexwforsythe/code-blocks#18]
When I try to select a portion of the text and click preview, I get:
```
Couldn't get theme.
```
I tried:

• reinstalling the add-on
• selecting a different theme
• changing the language
• selecting different text

The results are the same. Any suggestions?

**Comment by alexwforsythe** [comment]
That would indicate that the add-on is having trouble fetching the themes from the CDN or GH. I tried to reproduce the issue, but it seems to be working right now.

Can you try one more time? If you still encounter the error, please provide your language and theme selection. Thanks.

**Comment by ursuad** [comment]
Yes, now it seems to be working again. 👍
