### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by alexwforsythe** [alexwforsythe/code-blocks#2]
- [ ] Dockerfile
- [ ] Go
- [ ] Lua
- [ ] Scala
- [ ] Swift
- [ ] Thrift
- [ ] YAML

**Comment by dylan1406599** [comment]
Lua?

**Comment by alexwforsythe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [froo](https://trello.com/c/7G3BGEpS/6-froo)
