### ISSUE TITLE
CodeBlocks does not open the next day.

### ISSUE THREAD

**Issue by lobomacz** [alexwforsythe/code-blocks#23]
Hello.
I've installed code blocks last night and it worked nicely. However, this morning the option to start the app is not there. I cannot open code blocks to keep working on my document.

**Comment by alexwforsythe** [comment]
Hi, Marvin. The add-on is still there on my account, so I'm guessing it got uninstalled for you somehow. Could you try installing it again from the `Addons > Get-addons...` menu?

Also, keep in mind that Code Blocks does not work on spreadsheets or presentations. Only documents.

**Comment by Andrea** [comment]
same thing happening to me

**Comment by alexwforsythe** [comment]
I have deployed a new version of the add-on. You may be prompted to reinstall it. If are still having issues, please let me know!

**Comment by njncalub** [comment]
Hi,
sorry to hijack this. Code Blocks was working a few hours ago but then the 1.3.0 update broke it. The Highlight button is now disabled and I can't do anything.
