### ISSUE TITLE
Vendor dependencies to minimize permissions and load time

### ISSUE THREAD

**Issue by VladoJ** [alexwforsythe/code-blocks#24]
Hi Alex,

Your addon looks great and usefull, can I ask you about security? :)
Can I believe it is secure? 
For example, why it need connection to external services?

Thank you,

Vladimir

**Comment by alexwforsythe** [comment]
Hi, Vladimir. Code Blocks only connects to external services by making secure HTTP requests to cdnjs.com and github.com via the `UrlFetchApp`. These requests are used to fetch JS libraries and CSS files for theme styles. You can see these calls in [main.gs](https://github.com/alexwforsythe/code-blocks/blob/master/main.gs).

If all the requirements could be saved to this repository before each deployment, there would be no need for the external services permission. I can work on making script for this. We'll use this issue to track progress.

**Comment by VladoJ** [comment]
Hi Alex, thank you much for the explanation.
Feel free to keep this issue to track the progress.

By the way, it may be fine to include also material theme to the addon (https://github.com/equinusocio/material-theme) - it has a lot of fans, I like dark version.

**Comment by alexwforsythe** [comment]
The new version is deployed and no longer requires permission to access external services. You may be prompted to reinstall the add-on.
