### ISSUE TITLE
Eats a line of code

### ISSUE THREAD

**Issue by tessanijssen** [alexwforsythe/code-blocks#27]
When I try to use codeblocks, sometimes instead of highlighting properly, it deletes the last line of the code I'm trying to format. For reference, the snippet is in C++ and I'm highlighting with the settings language: cpp and theme: googlecode.

**Comment by tessanijssen** [comment]
Also, the preview shows up fine.

**Comment by tessanijssen** [comment]
Turns out I was accidentally putting the unhighlighted code in the same table as previously highlighted code.

**Comment by alexwforsythe** [comment]
Glad it worked out 😄
