### ISSUE TITLE
Addon returning 'ScriptError' when pressing the 'Preview' or 'Highlight' button

### ISSUE THREAD

**Issue by niels-nijens** [alexwforsythe/code-blocks#28]
I used this really nice Google Docs addon yesterday for a highlighting a few code examples in documentation I'm writing. Alas, today it isn't working and returns the following error:
```
ScriptError: Invalid argument: .hljs{display:block;overflow-x:auto;padding:.5em;background:#f0f0f0}.hljs,.hljs-subst{color:#444}.hljs-comment{color:#888}.hljs-attribute,.hljs-doctag,.hljs-keyword,.hljs-meta-keyword,.hljs-name,.hljs-selector-tag{font-weight:700}.hljs-deletion,.hljs-number,.hljs-quote,.hljs-selector-class,.hljs-selector-id,.hljs-string,.hljs-template-tag,.hljs-type{color:#800}.hljs-section,.hljs-title{color:#800;font-weight:700}.hljs-link,.hljs-regexp,.hljs-selector-attr,.hljs-selector-pseudo,.hljs-symbol,.hljs-template-variable,.hljs-variable{color:#bc6060}.hljs-literal{color:#78a960}.hljs-addition,.hljs-built_in,.hljs-bullet,.hljs-code{color:#397300}.hljs-meta{color:#1f7199}.hljs-meta-string{color:#4d99bf}.hljs-emphasis{font-style:italic}.hljs-strong{font-weight:700}
```

I've also tried using the addon in an entirely empty Google doc, but that would not solve the issue either.

**Comment by avi91** [comment]
I got the same the error. Look into this issue.

**Comment by avi91** [comment]
Allow **popups** on that site, it will solve the issue!

![See this screenshot](https://user-images.githubusercontent.com/10992908/29116774-95de1696-7d19-11e7-9d35-0a6847801490.png)

Because you are using a Webkit-based browser, most likely Chrome. This error message (introduced here) is displayed when an <iframe> element with sandbox attribute is attempting to run JavaScript (only allowed when allow-scripts is specified in that attribute).
Hope this helps :+1:

**Comment by amharF** [comment]
In my case that permission is set and the error no longer appears in the tool pane. However the theme from the preview  is not applied to the document.

**Comment by alexwforsythe** [comment]
Thanks for reporting this. The issue should be resolved now. Let me know if you're still experiencing any issues.

**Explanation:**
There seems to be an issue where the same script-level cache is used for both the production add-on *and* test versions. This is causing my development changes to have negative side-effects on the production add-on. Now that I'm aware of the issue, I can be more careful with my changes.

**Comment by niels-nijens** [comment]
It's working again. Thanks! 👍

**Comment by alexwforsythe** [comment]
Great, thanks again for reporting!
