### ISSUE TITLE
Insert Button Missing

### ISSUE THREAD

**Issue by whbldhwj** [alexwforsythe/code-blocks#29]
Hi,

I'd like to first thank the author for making such a helpful tool.
I was using it early this week and everything worked pretty well.
But today when I opened the add-on in my Google Doc, I found that I can no longer find the Insert button in the GUI. I tried different browsers and they all had the same problem. Besides, if I use the Highlight button, my code in the doc will be deleted instead of being highlighted. Is this supposed to be a bug? Please let me know how to fix it.

Thanks,
Jie

**Comment by alexwforsythe** [comment]
Hi, Jie. I deployed an update to the add-on yesterday and removed the **Paste** button intentionally. It was removed because users found it confusing to have 2 buttons (**Paste** & **Highlight**) that insert highlighted text into the document.

The **Highlight** button should replace your current selection with the highlighted text. If it isn't working for you, can you please provide the language, theme, and code snippet that you're trying to highlight? Thanks.

**Comment by whbldhwj** [comment]
Thanks for your quick reply! I used this code snippet.
```
for (i = 0; i < number; i++){
  wed_ptr->status = 1;
  while(wed_ptr->status != 2){
  }
}
```
I first select the code and pressed the preview. The highlighted code in the preview window looks fine. Then I pressed the highlight. The code will be deleted then.
I set language as auto and the theme as xcode.

**Comment by alexwforsythe** [comment]
Oddly, it seems to be working for me:
![image](https://user-images.githubusercontent.com/1639061/29226399-c9c9e084-7e86-11e7-9587-b196d5de3983.png)

Double-check that your selection is from the `f` in `for` to the last `}`. If it still doesn't work, can you try checking your browser JavaScript console for logs? If there aren't any errors there, please try reinstalling the add-on.

**Comment by whbldhwj** [comment]
It now works! I moved the code snippet to another place in my doc and tried the highlight again. I'm not sure what happened... But it's great that it works again. Thanks for your help! Have a good day!

**Comment by alexwforsythe** [comment]
No problem! If you have any ideas of how to reproduce the issue, feel free to let me know and I can work on a fix. Enjoy 😄
