### ISSUE TITLE
How to reset and change the code block theme. Can't insert here.

### ISSUE THREAD

**Issue by zymr-keshav** [alexwforsythe/code-blocks#38]
OS: macOS v 10.12.6
Google Chrome: 61

What I did:
I have applied one code-block theme now want to change or remove the theme .

What i Tried

1. Select the text block 
2. Now select **Add-ons > Code-Block > Start**  in Google Docs menu  and change theme from drop down

> language : auto
> Theme : monokai-sublime

Now I want to change the theme only so again select the text block and tried change theme

sometime it give error  _Can't insert here_.  below the preview box.

Will someone please specify how to apply or change theme or revert back to previous position of document

What I do right now is to copy the content within code-bloc , delete the code-block and paste the text with clear formatting option.

**Comment by zenchua** [comment]
I have the same issue but I figure out how to fix it.

The formatting currently doesn't work within table cells. Each time the format happens, a 1x1 table is created and the code snippets are written in the cell with the theme applied. i believe the table is to apply the background color.

If you need to change theme, you will need to cut out the code snippet within the cell. Delete the table (its invisible). Paste the snippet again and apply the new theme.

Hope this make sense.

**Comment by alexwforsythe** [comment]
@zenchua is right. In the future, I plan to support reformatting a code block with the **Format** button if the cursor is inside the table cell and no text is selected. For now, the easiest way to try out different themes is to format your code block, then click the **Undo** button in the toolbar (<kbd>Command</kbd>+<kbd>Z</kbd> on OS X or <kbd>Control</kbd>+<kbd>Z</kbd> on Windows) if you want to try again.
