### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by alexwforsythe** [alexwforsythe/code-blocks#4]

**Comment by roytseng-tw** [comment]
Look forward to have some handy shortcuts~  😃

**Comment by alexwforsythe** [comment]
Keyboard events in the active document cannot be handled by add-ons, oddly enough. See their [issue tracker](https://code.google.com/p/google-apps-script-issues/issues/detail?id=306).

I can add shortcuts that will work if the sidebar is focused, but that still requires a click. This is an impossible feature for the time being.
