### ISSUE TITLE
Question: Unformating Text

### ISSUE THREAD

**Issue by jennykortina** [alexwforsythe/code-blocks#41]
This isn't an issue, just a question:

 If I format something as code, close the doc or do a bunch of other changes in the doc, how do I unformat the code block back to standard text?

Thank you!

**Comment by alexwforsythe** [comment]
You can clear formatting in Google Docs by highlighting the text and selecting `Format > Clear Formatting` from the toolbar. The keyboard shortcut is <kbd>Cmd</kbd>+<kbd>/</kbd> on OS X and <kbd>Ctrl</kbd>+<kbd>/</kbd> on Windows: https://support.google.com/docs/answer/179738

This will not remove the table that the text lives in if it's a "code block". To do that, you'll have to copy the text and paste it outside the table, then right-click the table and select **Delete table**.

**Comment by jennykortina** [comment]
Thank you!
