### ISSUE TITLE
Trim permissions

### ISSUE THREAD

**Issue by aggieben** [alexwforsythe/code-blocks#58]
This extension looks very nice, but I have a concern similar to #24: would it be reasonably possible to trim the required permissions further?  Does this extension need the ability to:

- manage documents
- share documents
- run in the background
?

All of these are problematic for use with a business account where proprietary information may be stored.

**Comment by alexwforsythe** [comment]
Thanks for raising the issue! I agree those permissions are problematic for both business and personal use, nor should they all be necessary for Code Blocks to do its job.

From a quick search, I found out that OAuth scopes are detected and required automatically based on references to script services (e.g. `ScriptApp`) anywhere inside the add-on code. This applies to services even if they are never invoked. The culprit in this case was a docstring I had copied from the official GAS docs along with the initial boilerplate code for this add-on.

---
**Sources**
* https://stackoverflow.com/a/48200656/3314534
* https://developers.google.com/apps-script/concepts/scopes

**Comment by alexwforsythe** [comment]
This seems to be the best I can do:
![image](https://user-images.githubusercontent.com/1639061/36296250-3fa047b8-12a1-11e8-9e14-e02b147fb27c.png)

**Comment by aggieben** [comment]
Thanks, this may be good enough.  "share documents" and "run in the background" were the most worrisome.

**Comment by aiyerkvdnc** [comment]
It seems like the required scopes still includes run in the background. Is this a regression?
![Screenshot 2020-03-04 at 4 48 56 PM](https://user-images.githubusercontent.com/54079690/76031476-c30b6300-5f05-11ea-8a5f-f455b1e7fe48.png)

**Comment by 414n** [comment]
I also see an additional "display your personal data, including those that you made public" (translated from my language, apologies it that is not the exact string) permission request.
