### ISSUE TITLE
Couldn't get theme

### ISSUE THREAD

**Issue by dfrechette** [alexwforsythe/code-blocks#59]
Hello, I'm having a similar issue with the docco theme. I have tried reloading the document, opening the document in a new tab, I get the same error every time. When I change themes, e.g. default, it works.

<img width="302" alt="screen shot 2018-02-07 at 20 12 18" src="https://user-images.githubusercontent.com/14079/35950386-4d26b920-0c44-11e8-82a1-3413940291c1.png">

Thank you for your support.

**Comment by dfrechette** [comment]
The theme is back. Problem solved.

**Comment by alexwforsythe** [comment]
Glad it worked out. Feel free to reopen this if you run into the issue again.

**Comment by indianazhao** [comment]
This problem occurs again today. Could you please check it? Thank you!
