### ISSUE TITLE
Problema com os valores hexadecimais

### ISSUE THREAD

**Issue by Maharal** [alexwforsythe/code-blocks#67]
O programa não formata corretamente os valores em hexadecimal(tipo: #ffffff) no tema arta da linguagem processing.

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> Code Blocks is built with [highlight.js](https://highlightjs.org/) and can only provide syntax highlighting for languages that are supported by that library.
>
> If you'd like to see Code Blocks support a language that is not yet implemented by highlight.js, please refer to [their page on requesting new languages](http://highlightjs.readthedocs.io/en/latest/language-requests.html).
