### ISSUE TITLE
code blocks does not appear under Add-ons toolbar in google docs

### ISSUE THREAD

**Issue by mardi08** [alexwforsythe/code-blocks#76]
added the add-ons
![image](https://user-images.githubusercontent.com/25186507/39951721-a26437c8-555a-11e8-9ce6-f95bf4305b76.png)

then nothing
![image](https://user-images.githubusercontent.com/25186507/39951738-d24a5846-555a-11e8-8869-d909c66e183d.png)

**Comment by alexwforsythe** [comment]
Hi @mardi08. This issue comes up once in awhile (see #66, #70). Please try reinstall the add-on. If that doesn't work, feel free to reopen the issue.

**Comment by mardi08** [comment]
the issue appeared to be unique to certain files. some google docs files don't have such problems but files who had the problem since the time of the file creation could not be resolved by reinstall the add-on. I have tried that.
