### ISSUE TITLE
ScriptError   - Authorization is required to perform that action

### ISSUE THREAD

**Issue by Georgio32** [alexwforsythe/code-blocks#78]
I am attempting to format some MatLab code, and this error appears. Have I failed to install the add-on appropriately?

**Comment by leoadnan** [comment]
I am also getting same error.

**Comment by alexwforsythe** [comment]
Hi @Georgio32 and @leoadnan. Thanks for reporting the issue! We are currently tracking this error in #53, so I'm going to close this as a duplicate.

The short explanation is that this is a bug with Google App Script which occurs when you have multiple accounts logged into Drive. You should be able to work around it by logging out of all accounts except the one you need to edit the document.
