### ISSUE TITLE
Theme list cuts off after solarized-dark?

### ISSUE THREAD

**Issue by giggsey** [alexwforsythe/code-blocks#8]
The theme drop down only shows up to solarized-dark, whereas the [JSON source](https://api.github.com/repos/highlightjs/cdn-release/contents/build/styles) contains 11 more items.

**Comment by alexwforsythe** [comment]
I'm grabbing the filenames from the latest version returned by the [API](https://api.cdnjs.com/libraries/highlight.js). Looks like version 9.8.0 is missing those last few themes. We can go back to 9.7.0 until they get added back to a future version.
