### ISSUE TITLE
Not showing as add-on

### ISSUE THREAD

**Issue by lwallmba** [alexwforsythe/code-blocks#80]
I installed the add-on but there is nothing to click in the Add-Ons menu.

**Comment by alexwforsythe** [comment]
Hi @lwallmba. Can you try refreshing your document a few times to see if it starts working? Also, can you check if the add-on works in a new document? Some users have reported that the add-on doesn't show up in certain files for some reason.

**Comment by mardi08** [comment]
try to reset your browser settings

if you are using chrome, this might work.

especially if you have many chrome extensions installed on your browser.

**Comment by alexwforsythe** [comment]
Closing as a duplicate of #77
