### ISSUE TITLE
ScriptError

### ISSUE THREAD

**Issue by dmnkkrst** [alexwforsythe/code-blocks#82]
Since yesterday I receive this error message as soon as I try to execute code blocks.

> ScriptError: We're sorry, a server error occurred. Please wait a bit and try again.

**Comment by alexwforsythe** [comment]
That seems like it could be a transient error with Google Apps Script. Can you still reproduce the error?

**Comment by alexwforsythe** [comment]
Closing this out because it's been a couple months with no update. Feel free to reopen if you see the issue again.

**Comment by zeilerphone** [comment]
I got this issue, no idea why. Tried on different computers also.

**Comment by filimongeorge** [comment]
I also got this issue, happening for a couple of days now. Worked when I first used the Add-On, but the next day I started getting the issue when trying to format the code.

@alexwforsythe

**Comment by GabrieleCalarota** [comment]
Reopening cause I'm seeing the error now (worked for the first half of the day).

`ScriptError: We're sorry, a server error occurred. Please wait a bit and try again.`

![image](https://user-images.githubusercontent.com/20482413/118791426-fcc05380-b896-11eb-9c6f-ace5da521425.png)
