### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mfarrugi** [alexwforsythe/code-blocks#84]
Corporate users have a generally bad time adding gsuite plugins, so deploying our own copy would be one alternative. There is currently no (permissive) license, which prevents us from doing so.

This was also expressed in #45.

**Comment by alexwforsythe** [comment]
The MIT OSS license has been added to the repository by @abeaclark. Cheers!

**Comment by abeaclark** [comment]
Thanks @alexwforsythe!
