### ISSUE TITLE
Can't insert code snippet in existing table

### ISSUE THREAD

**Issue by hakkas** [alexwforsythe/code-blocks#9]
It's not possible to paste a code snippet into an existing table.

**Comment by vibs2006** [comment]
Yes I also cannot reformat code inside a table cell however its working fine outside. 

![image](https://user-images.githubusercontent.com/18658498/29356192-14e50f40-8291-11e7-8239-0524b1baec04.png)

**Comment by alexwforsythe** [comment]
One of the main features of this add-on is to save time by creating the table for you, so it doesn't support highlighting an existing table. I'll consider adding support, but could you first explain why you want to create the table manually so I can understand your use-case?

**Comment by vibs2006** [comment]
@alexwforsythe thanks for replying, As far as use case is concerned then I have been storing notes in a format with two table columns which saves my codes references i.e 1st column contains the concept and another column contains the code. 

Example something like this 
![image](https://user-images.githubusercontent.com/18658498/29394017-5149bcc6-8325-11e7-89f9-b34cc62e04e4.png)

**Comment by alexwforsythe** [comment]
Cool. I'll make this the next feature addition. The behavior will be like this:
1. If you selected text in a cell, replace it with a new 1x1 formatted table inside that cell
2. If you didn't select text, format the entire cell where your cursor is located

**Comment by vibs2006** [comment]
@alexwforsythe Thanks if this can be added then it'll be very helpful.
