### ISSUE TITLE
Valid ES6 code breaks formatting

### ISSUE THREAD

**Issue by xthilakx** [alexwforsythe/code-blocks#91]
When I try to format this ES6 code using code blocks addon, it breaks formatting. 

Language used: JavaScript;
Theme: Dracula. 

```js
function isEqual(value, compare = 10/2) {
	console.log(value); // output: 5
	console.log(compare); // output: 5
	return value == compare;
}

console.log(isEqual(5)); // output: true
```

Screenshot: https://imgur.com/a/gec3YEt

**Comment by alexwforsythe** [comment]
From the [README](https://github.com/alexwforsythe/code-blocks#updates-to-syntax-highlighting):
> Code Blocks is built with [highlight.js](https://highlightjs.org/) and can only provide syntax highlighting for languages that are supported by that library.
>
> If you'd like to see Code Blocks support a language that is not yet implemented by highlight.js, please refer to [their page on requesting new languages](http://highlightjs.readthedocs.io/en/latest/language-requests.html).
