### ISSUE TITLE
could't get theme

### ISSUE THREAD

**Issue by xstargazer** [alexwforsythe/code-blocks#92]
![image](https://user-images.githubusercontent.com/25920970/43388343-6ef9164c-941b-11e8-8287-e23e4ed246e0.png)

**Comment by shwuj** [comment]
same here

**Comment by amishshah** [comment]
Happens to me too when I try using the `github` theme, worked fine and then suddenly stopped working, other themes (including `github gist`) seem to work fine

**Comment by amishshah** [comment]
Seems to be fixed for me now FWIW

**Comment by alexwforsythe** [comment]
This should be fixed! Feel free to reopen if you see the error again
