### ISSUE TITLE
Continually update the code block

### ISSUE THREAD

**Issue by evandrocoan** [alexwforsythe/code-blocks#96]
Once I am inside a formatted, table I can edit the code, but not new highlighting is applied. I have to keep reelecting the code, cleaning the formatting and reapplying.

**Comment by alexwforsythe** [comment]
Hi @evandrocoan. Thanks for the suggestion. I don't have any plans to support continual updates at this time.

You should be able to easily reformat a code block by simply placing your cursor inside the block and clicking **Format** again. No highlighting necessary. I hope this helps fix your issue.
