### ISSUE TITLE
ScriptError: Authorization is required to perform this action.

### ISSUE THREAD

**Issue by ExpectedMoss0** [alexwforsythe/code-blocks#99]
What's going on?

**Comment by PriyanshuAgarwal** [comment]
Yes, I am getting the same error

**Comment by alexwforsythe** [comment]
Hi @ExpectedMoss0 & @PriyanshuAgarwal. We are currently tracking this error in #53, so I'm going to close this as a duplicate.

The short explanation is that this is a bug with Google App Script which occurs when you have multiple accounts logged into Drive. You should be able to work around it by logging out of all accounts except the one you need to edit the document.
